
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#      database-platform: org.hibernate.dialect.MySQLDialect
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

server:
  port: ${SERVER_PORT}

  application:
    name: E-service

#  profiles:
#    active: dev
